### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid document reference. Document references must have an even number of segments, but users has 1

### ISSUE THREAD

**Issue by joelkanyi** [robert-muriithi/Tasks-App-Compose#60]
When I logged in for the first time after creating an account and I had clicked on sign in with google, the app crashed with the following exception:

```
java.lang.IllegalArgumentException: Invalid document reference. 
Document references must have an even number of segments, but users has 1
```

Steps to replicate:
1. Launch the app for the first time (Emulator)
2. Click on Sign in with Google
3. Click on Register
4. Do the Registration
5. The textfield for email and password are unresponsive, so I destroyed the app and launched again (maybe this is just an issue from my end)
6. Try to login with the account you had registered
7. The app crashes

**Comment by robert-muriithi** [comment]
Hi @joelkanyi 

Thank you for raising this. I will have a look into it
